---
title: "webpage"
format: html
---

```{r, warning=FALSE}
library(ggplot2)
library(ggarrow)

```

```{r}
# Variables for the coordinate plane
xlim <- c(0, 100)
ylim <- c(0, 100)
    
# Start point is the center of the plot at (50,50)
x0 <- 50
y0 <- 50

# "User input"
angle <- 90  
r <- 40

```


```{r}
# Convert degrees to radians to be put into cos and sin >> angle * pi / 180

# Google Gemini calculations to allow clockwise direction

# The direction a line points will be based on the angle so find the endpoint by multiplying the angle by the radius + starting point
x1 <- x0 + r * sin(angle * pi / 180)
y1 <- y0 + r * cos(angle * pi / 180)

# Draw the cartesian plot
ggplot() +
  geom_segment(
    aes(x = x0, y = y0, xend = x1, yend = y1), 
    linewidth = 1,
    arrow = arrow(length = unit(r, "points"))
  ) +
  coord_fixed(xlim = xlim, ylim = ylim) +
  theme_void()
```

## Making a Polar Plot version of the above

```{r}
# A dataframe to preserve the values to be able to apply coord_polar
df <- data.frame(
  angle = angle, # user's input
  radius = r # the set radius
)
```


```{r}
# Draw the polar plot
ggplot(df) +
  geom_segment(
    aes(x = angle, y = 0, xend = angle, yend = radius), # start and end for the polar plot is the angle for xvalues
    arrow = arrow(length = unit(r, "points")),
    linewidth = 1
  ) +
  scale_x_continuous(limits = c(0, 360), breaks = seq(0, 360, by = 45)) + # Set x-axis to 360 degrees
  coord_polar(theta = "x", start = 0, direction = 1) + # clockwise direction
  theme_void() 
```


# Variables
    xlim <- c(0, 100)
    ylim <- c(0, 100)
    
    # Make a plot and add the image on top of it
    ggplot() +
      coord_fixed(xlim = xlim, ylim = ylim) +
      theme_minimal() +
      theme(
        axis.text = element_blank(),
        axis.title = element_blank(),
        axis.ticks = element_blank()
      ) + 
      geom_image(aes(x = 50, y = 50, image = img_url), 
                 size = 1.5) 
   














