---
title: "windanalysis"
format: html
author: Francesca Mnenula
---

### About

This qmd file will analyse weather data retrieved from the St. Lawrence Living Lab.

```{r, warning=FALSE, message=FALSE}
# Load libraries
library(readr)
library(tidyverse)
```

```{r, message=FALSE, warning=FALSE}
# Read in csv files
file <- "../winddata/winddata.csv"
wind_csv <- read_csv(file)
```


```{r, message=FALSE, warning=FALSE}
# Rename columns
wind_csv <-
  wind_csv %>%
  mutate(
    X1 = as.Date(X1)
  ) %>%
  rename(
    date = X1
  ) %>%
  group_by(date) %>%
  summarise(
    X2 = mean(X2),
    X3 = mean(X3),
    X4 = mean(X4),
    X5 = mean(X5),
    X6 = mean(X6),
    X7 = mean(X7),
    X8 = mean(X8),
    X9 = mean(X9),
    X10 = mean(X10),
    X11 = mean(X11),
    X12 = mean(X12),
    X13 = mean(X13),
    X14 = mean(X14),
    X15 = mean(X15),
    X16 = mean(X16),
    X17 = mean(X17),
    X18 = mean(X18),
    X19 = mean(X19),
    X20 = mean(X20),
    X21 = mean(X21),
    X22 = mean(X22),
    X23 = mean(X23)
  )
```


```{r}
wind_csv
```

